import { useState, useCallback, useEffect } from 'react';
import PropTypes from 'prop-types';
import ScoreGauge from './ScoreGauge';
import { STORAGE_KEYS } from '../utils/constants';

/**
 * @typedef {Object} Recommendation
 * @property {string} title - Actionable recommendation title
 * @property {string} description - Comprehensive advice description
 * @property {number} estimatedCO2Saved - Estimated CO2 savings in kg/week
 */

/**
 * @typedef {Object} DayTask
 * @property {number} day - The index of the day (1-7)
 * @property {string} task - The challenge action item
 */

/**
 * @typedef {Object} CoachPlan
 * @property {string} analysis - Deep contextual footprint review
 * @property {string} topEmissionSource - Highest emission driver ('transport' | 'food' | 'electricity')
 * @property {string} topEmissionSourceExplanation - Details explaining the main driver
 * @property {Recommendation[]} recommendations - Exactly 5 specific tips
 * @property {Object} sevenDayChallenge - Weekly challenge parameters
 * @property {string} sevenDayChallenge.title - Title of the challenge
 * @property {DayTask[]} sevenDayChallenge.days - Exactly 7 daily items
 * @property {Object} predictedImprovement - Projected carbon savings details
 * @property {number} predictedImprovement.newScore - New Carbon Health Score (0-100)
 * @property {number} predictedImprovement.co2ReductionPercent - Percentage carbon reduced
 * @property {string} predictedImprovement.explanation - Rationale behind targets
 */

/**
 * AICoach component for EcoSense AI.
 * Queries Gemini for a custom action plan and renders the results.
 * 
 * @component
 * @param {Object} props - Component props
 * @param {number} props.score - The current Carbon Health Score
 * @param {Object} props.breakdown - Breakdown of current monthly emissions in kg CO2
 * @param {Object} props.rawInputs - Inputs mapped from the Calculator form
 * @param {function} [props.onPlanGenerated] - Callback triggered when predicted score is generated by AI
 * @returns {React.ReactElement} The AI Coach component
 */
export default function AICoach({ score, breakdown, rawInputs, onPlanGenerated }) {
  const [plan, setPlan] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [announcement, setAnnouncement] = useState('');
  const [openAccordion, setOpenAccordion] = useState({});
  const [checkedDays, setCheckedDays] = useState({});

  // Reset plan when the input data changes (encouraging new scans)
  useEffect(() => {
    setPlan(null);
    setError('');
  }, [score, breakdown, rawInputs]);

  // Load checked days progress from localStorage when the plan loads
  useEffect(() => {
    if (plan?.sevenDayChallenge?.title) {
      const storageKey = `${STORAGE_KEYS.CHALLENGE}-${plan.sevenDayChallenge.title.replace(/\s+/g, '_')}`;
      try {
        const saved = localStorage.getItem(storageKey);
        setCheckedDays(saved ? JSON.parse(saved) : {});
      } catch {
        setCheckedDays({});
      }
    }
  }, [plan]);

  // Save checked days progress to localStorage
  const handleCheckDay = useCallback((dayNum, isChecked) => {
    if (!plan?.sevenDayChallenge?.title) return;
    
    const storageKey = `${STORAGE_KEYS.CHALLENGE}-${plan.sevenDayChallenge.title.replace(/\s+/g, '_')}`;
    setCheckedDays((prev) => {
      const updated = { ...prev, [dayNum]: isChecked };
      try {
        localStorage.setItem(storageKey, JSON.stringify(updated));
      } catch {
        console.error('Failed to save progress to localStorage.');
      }
      return updated;
    });
  }, [plan]);

  const toggleAccordion = useCallback((index) => {
    setOpenAccordion((prev) => ({ ...prev, [index]: !prev[index] }));
  }, []);

  const handleGetPlan = useCallback(async () => {
    setIsLoading(true);
    setError('');
    setAnnouncement('Consulting your AI Carbon Coach...');

    try {
      const response = await fetch('/api/carbon-coach', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          carbonScore: score,
          transport: rawInputs?.transport || 0,
          food: rawInputs?.foodHabit || 'veg',
          electricity: rawInputs?.electricity || 0
        })
      });

      const result = await response.json();

      if (!response.ok || !result.success) {
        throw new Error(result.message || 'Failed to fetch coaching plan.');
      }

      setPlan(result.data);
      setAnnouncement('AI Carbon Action Plan successfully loaded.');
      if (onPlanGenerated && result.data?.predictedImprovement?.newScore !== undefined) {
        onPlanGenerated(result.data.predictedImprovement.newScore);
      }
    } catch (err) {
      console.error(err);
      let errorMsg = 'Failed to retrieve your carbon action plan. Check your server settings and try again.';
      
      if (err.message.includes('429')) {
        errorMsg = 'The AI Coach is currently busy helping other users. Please try again in a few moments.';
      } else if (err.name === 'TypeError' || err.message.includes('fetch')) {
        errorMsg = 'Unable to connect to the coaching server. Please verify the backend service is running.';
      }
      
      setError(errorMsg);
      setAnnouncement(`Coaching error: ${errorMsg}`);
    } finally {
      setIsLoading(false);
    }
  }, [score, rawInputs, onPlanGenerated]);

  // Dynamic Icon selector for top emission category
  const renderSourceIcon = (source) => {
    switch (source?.toLowerCase()) {
      case 'transport':
        return (
          <div className="w-12 h-12 rounded-xl bg-amber-500/10 flex items-center justify-center text-amber-400 border border-amber-500/20" aria-hidden="true">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z" />
            </svg>
          </div>
        );
      case 'food':
        return (
          <div className="w-12 h-12 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-400 border border-emerald-500/20" aria-hidden="true">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 3c-1.2 0-2.4 1.2-3 2.4-1.2 0-2.4 1.2-2.4 2.4 0 1.2 1.2 2.4 2.4 3 0 1.2 1.2 2.4 2.4 2.4 1.2 0 2.4-1.2 3-2.4 1.2 0 2.4-1.2 2.4-2.4 0-1.2-1.2-2.4-2.4-3 0-1.2-1.2-2.4-2.4-2.4z" />
            </svg>
          </div>
        );
      case 'electricity':
      default:
        return (
          <div className="w-12 h-12 rounded-xl bg-teal-500/10 flex items-center justify-center text-teal-400 border border-teal-500/20" aria-hidden="true">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
        );
    }
  };

  return (
    <div className="w-full mt-10">
      <div className="sr-only" aria-live="polite" role="status">
        {announcement}
      </div>

      {/* 1. Request Plan Trigger (Initial State) */}
      {!plan && !isLoading && (
        <div className="text-center p-8 bg-slate-900/20 border border-slate-800 rounded-3xl backdrop-blur-xs">
          <h3 className="text-lg font-bold font-display text-white mb-2">
            Get Personalized Action Coach Insights
          </h3>
          <p className="text-slate-400 text-sm max-w-lg mx-auto mb-6">
            Leverage Google Gemini Generative AI to scan your profile data and build a customized eco-challenge action list.
          </p>
          <button
            onClick={handleGetPlan}
            className="px-8 py-3.5 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-bold shadow-lg hover:shadow-emerald-500/10 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950"
          >
            Get My AI Action Plan
          </button>
        </div>
      )}

      {/* 2. Loading State */}
      {isLoading && (
        <div className="text-center py-16 bg-slate-900/20 border border-slate-800 rounded-3xl backdrop-blur-xs flex flex-col items-center justify-center">
          <svg className="animate-spin h-10 w-10 text-emerald-500 mb-4" fill="none" viewBox="0 0 24 24" aria-hidden="true">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          <p className="text-slate-300 font-semibold text-lg">Consulting AI Carbon Coach...</p>
          <p className="text-slate-400 text-xs mt-2">Formulating actionable carbon reductions based on your stats...</p>
        </div>
      )}

      {/* 3. Error Feedback */}
      {error && !isLoading && (
        <div className="p-6 bg-red-500/10 border border-red-500/20 rounded-3xl flex flex-col md:flex-row items-center md:items-start space-y-4 md:space-y-0 md:space-x-4 text-center md:text-left">
          <div className="w-12 h-12 rounded-xl bg-red-500/20 flex items-center justify-center text-red-400 shrink-0">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          </div>
          <div>
            <h4 className="text-md font-bold text-white mb-1">Coaching Generation Error</h4>
            <p className="text-red-400 text-sm">{error}</p>
            <button
              onClick={handleGetPlan}
              className="mt-4 px-5 py-2.5 bg-slate-900 border border-slate-800 text-white text-xs font-semibold rounded-lg hover:bg-slate-850 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-700"
            >
              Retry Consultation
            </button>
          </div>
        </div>
      )}

      {/* 4. Display Recommendations Layout */}
      {plan && !isLoading && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Left Block: Analysis & Recommendations list */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* Analysis card */}
            <article className="bg-slate-900/40 border border-slate-800/80 rounded-2xl p-6 backdrop-blur-sm shadow-xl">
              <h4 className="text-lg font-bold font-display text-white mb-3">AI Coach Analysis</h4>
              <p className="text-slate-300 text-sm leading-relaxed whitespace-pre-line">{plan.analysis}</p>
            </article>

            {/* Top emission driver */}
            <article className="p-6 bg-slate-900/40 border border-slate-800/80 rounded-2xl flex items-start space-x-4">
              {renderSourceIcon(plan.topEmissionSource)}
              <div>
                <h4 className="text-sm font-semibold uppercase tracking-wider text-slate-400">Primary Emission Driver</h4>
                <p className="text-lg font-bold text-white capitalize mt-0.5">{plan.topEmissionSource}</p>
                <p className="text-slate-400 text-xs mt-1 leading-relaxed">{plan.topEmissionSourceExplanation}</p>
              </div>
            </article>

            {/* Expandable Recommendations Accordion */}
            <section aria-label="Action Recommendations List" className="space-y-3">
              <h4 className="text-lg font-bold font-display text-white mb-2 px-1">Top Actionable Steps</h4>
              {plan.recommendations.map((rec, i) => {
                const isOpen = !!openAccordion[i];
                return (
                  <article 
                    key={i} 
                    className="border border-slate-850 rounded-xl bg-slate-900/20 hover:border-slate-800 transition-colors overflow-hidden"
                  >
                    <button
                      onClick={() => toggleAccordion(i)}
                      aria-expanded={isOpen}
                      aria-controls={`rec-desc-${i}`}
                      className="w-full flex justify-between items-center p-4 text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 rounded-xl"
                    >
                      <div className="flex items-center space-x-3 pr-2">
                        <span className="w-6 h-6 rounded-full bg-slate-800 flex items-center justify-center text-xs text-slate-400 font-bold shrink-0">{i + 1}</span>
                        <span className="text-sm font-semibold text-white tracking-tight">{rec.title}</span>
                      </div>
                      <div className="flex items-center space-x-3 shrink-0">
                        <span className="px-2.5 py-1 text-[10px] font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 rounded-full">
                          -{rec.estimatedCO2Saved} kg/wk
                        </span>
                        <svg 
                          className={`w-4 h-4 text-slate-400 transition-transform ${isOpen ? 'rotate-180' : ''}`} 
                          fill="none" 
                          stroke="currentColor" 
                          viewBox="0 0 24 24"
                          aria-hidden="true"
                        >
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                        </svg>
                      </div>
                    </button>
                    {isOpen && (
                      <div 
                        id={`rec-desc-${i}`} 
                        className="p-4 pt-0 border-t border-slate-900 text-xs text-slate-400 leading-relaxed"
                      >
                        {rec.description}
                      </div>
                    )}
                  </article>
                );
              })}
            </section>
          </div>

          {/* Right Block: Challenge & Score Targets */}
          <div className="lg:col-span-5 space-y-6">
            
            {/* 7-Day Challenge checklist */}
            <section className="bg-slate-900/40 border border-slate-800/80 rounded-2xl p-6 backdrop-blur-sm shadow-xl">
              <div className="mb-4">
                <span className="text-[10px] font-bold bg-teal-500/10 text-teal-400 border border-teal-500/20 px-2 py-0.5 rounded-full uppercase tracking-wider">
                  Weekly Goal
                </span>
                <h4 className="text-lg font-bold font-display text-white mt-2">
                  {plan.sevenDayChallenge.title}
                </h4>
              </div>

              <div className="space-y-3 mt-4" role="group" aria-label="7 day checklist items">
                {plan.sevenDayChallenge.days.map((item, idx) => {
                  const isChecked = !!checkedDays[item.day];
                  return (
                    <div 
                      key={idx} 
                      className={`flex items-start space-x-3 p-3 rounded-xl border transition-all ${
                        isChecked 
                          ? 'border-emerald-500/20 bg-emerald-500/5' 
                          : 'border-slate-850 hover:border-slate-800 bg-slate-950/20'
                      }`}
                    >
                      <input
                        type="checkbox"
                        id={`day-chk-${item.day}`}
                        checked={isChecked}
                        onChange={(e) => handleCheckDay(item.day, e.target.checked)}
                        className="w-4 h-4 rounded border-slate-800 text-emerald-500 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 focus-visible:ring-offset-slate-950 bg-slate-950/80 mt-0.5 accent-emerald-500 cursor-pointer"
                        aria-label={`Mark Day ${item.day} challenge task as completed`}
                      />
                      <label 
                        htmlFor={`day-chk-${item.day}`} 
                        className={`text-xs select-none cursor-pointer leading-relaxed ${
                          isChecked ? 'line-through text-slate-400' : 'text-slate-300 hover:text-white'
                        }`}
                      >
                        <span className="font-bold text-slate-400 mr-1.5">Day {item.day}:</span>
                        {item.task}
                      </label>
                    </div>
                  );
                })}
              </div>
            </section>

            {/* Score Comparison Display */}
            <section className="bg-slate-900/40 border border-slate-800/80 rounded-2xl p-6 backdrop-blur-sm shadow-xl text-center">
              <h4 className="text-md font-bold font-display text-white mb-4">
                Projected Scoring Impact
              </h4>
              <div className="grid grid-cols-2 gap-4 items-center">
                <div>
                  <span className="text-xs text-slate-400 font-semibold uppercase block mb-2">Current Score</span>
                  <div className="scale-85 origin-center">
                    <ScoreGauge score={score} />
                  </div>
                </div>
                <div>
                  <span className="text-xs text-slate-400 font-semibold uppercase block mb-2">Projected Score</span>
                  <div className="scale-85 origin-center animate-pulse">
                    <ScoreGauge score={plan.predictedImprovement.newScore} />
                  </div>
                </div>
              </div>

              <div className="mt-6 pt-4 border-t border-slate-850">
                <div className="text-emerald-400 font-extrabold text-2xl">
                  -{plan.predictedImprovement.co2ReductionPercent}% CO2
                </div>
                <p className="text-[11px] text-slate-400 mt-2 leading-relaxed">
                  {plan.predictedImprovement.explanation}
                </p>
              </div>
            </section>
          </div>
        </div>
      )}
    </div>
  );
}

AICoach.propTypes = {
  score: PropTypes.number.isRequired,
  breakdown: PropTypes.shape({
    transport: PropTypes.number,
    food: PropTypes.number,
    electricity: PropTypes.number,
    total: PropTypes.number
  }).isRequired,
  rawInputs: PropTypes.shape({
    transport: PropTypes.number,
    foodHabit: PropTypes.string,
    electricity: PropTypes.number
  }).isRequired,
  onPlanGenerated: PropTypes.func
};

AICoach.defaultProps = {
  onPlanGenerated: () => {},
};

